ssh_daemon: '{{ cloud_init.system_info.ssh_svcname | default("sshd") }}'
chrony_service: '{{ ( ansible_facts.os_family == "Debian" ) | ternary("chrony", "chronyd") }}'
has_deb822: '{{
  ( ansible_facts.distribution == "Debian" and
    ansible_facts.distribution_major_version is version("13", "ge") )
  or
  ( ansible_facts.distribution == "Ubuntu" and
    ansible_facts.distribution_major_version is version("24", "ge") ) }}'
