cacert_path: '/opt/symas/ssl/ca.crt'
cacsr_path: '{{ cacert_path | splitext | first }}.csr'
cakey_path: '{{ cacert_path | splitext | first }}.key'
cert_path: '{{ cacert_path | dirname }}/{{ inventory_hostname }}.crt'
ca_host: '{{ groups.ca | first }}'
ca_dn: 'cn=testing,o=LDAPCon,l=Tubingen,c=DE'
subject_dn: 'cn={{ (inventory_hostname | split("."))[0] }},ou=hosts,{{ suffix }}'
subject_ordered: '{{ subject_dn | dn2subject_ordered }}'
participant: '.'
