- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart sshd
  systemd:
    name: '{{ ssh_daemon | default("sshd") }}'
    state: restarted

- name: update apt cache
  apt:
    update_cache: yes
